// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmWE5v2tnlkOJoBF5jyUs9V07Ha9Buqjw',
    appId: '1:603783555606:web:ee2d192d564a009e776337',
    messagingSenderId: '603783555606',
    projectId: 'easacc-task-aea3c',
    authDomain: 'easacc-task-aea3c.firebaseapp.com',
    storageBucket: 'easacc-task-aea3c.firebasestorage.app',
    measurementId: 'G-09KG7YNDPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiJ_L00T50YnqHjGuaupzdjwsFRFrTHQQ',
    appId: '1:603783555606:android:4b1d69cbd0f6b24f776337',
    messagingSenderId: '603783555606',
    projectId: 'easacc-task-aea3c',
    storageBucket: 'easacc-task-aea3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVna812BQjG8q9UtmOT5a7mPYoFne43Yw',
    appId: '1:603783555606:ios:e43bcf91bcc2a04d776337',
    messagingSenderId: '603783555606',
    projectId: 'easacc-task-aea3c',
    storageBucket: 'easacc-task-aea3c.firebasestorage.app',
    iosBundleId: 'com.example.easaccFlutterTask',
  );
}
